Feature/review
urfit-tech/lodestar-app pull request #1
Opened 2020-11-24 05:15 UTC by Ponchimeow

layout beta, will change a little design when all data concatenation.

2020-11-27 04:18 UTC, futianshen commented on src/components/common/CommonModal.tsx
>      renderFooter?: () => React.ReactElement
```js
title: string
renderTrigger: () => React.ReactElement
renderHeaderIcon?: () => React.ReactElement
renderFooter?: () => React.ReactElement
```

2020-11-27 04:19 UTC, futianshen commented on src/components/common/CommonModal.tsx
> +          {renderHeaderIcon && renderHeaderIcon()}
```jsx
{renderHeaderIcon?.()}
```

2020-11-27 04:23 UTC, futianshen commented on src/components/review/ReviewCollectionBlock.tsx
> +    return reviewCount === 0 ? 0 : (totalScore / reviewCount).toFixed(1)
reviewCount && (totalScore / reviewCount).toFixed(1)

2020-11-30 04:40 UTC, futianshen commented on src/components/review/ReviewReplyItem.tsx
> +  )
can use a custom hook to wrap it up
```
const { updateReviewReply, deleteReviewReply } = useMutateReviewReply(reviewReplyId, currentMemberId, appId)
```

2020-12-01 02:30 UTC, Elantris commented
![](https://github.trello.services/images/mini-trello-icon.png) [(8) 【評價】評價前台切版 [6]](https://trello.com/c/D1G3u4rl/1566-8-%E3%80%90%E8%A9%95%E5%83%B9%E3%80%91%E8%A9%95%E5%83%B9%E5%89%8D%E5%8F%B0%E5%88%87%E7%89%88-6)

2020-12-01 04:05 UTC, futianshen commented on src/components/review/ReviewAdminItem.tsx
> +      reviewId: v.id,
just use id

2020-12-01 04:05 UTC, futianshen commented on src/components/review/ReviewAdminItem.tsx
> +              key={uuid()}
why not use reviewId ?

2020-12-01 04:09 UTC, futianshen commented on src/components/review/ReviewMemberItem.tsx
> +    onRefetch: refetch,
use `refetch` or `refetchReviews`

2020-12-01 04:14 UTC, futianshen commented on src/components/review/ReviewAdminItem.tsx
> +      {!loadingReviews && loadMoreReviews && (
can add loading state before loading complete
```js
if (loadingReviews) {
  return
}

return  <>
      {reviews.map((v: ReviewProps) => { ...

```

2020-12-01 04:19 UTC, futianshen commented on src/components/review/ReviewAdminItem.tsx
> +          <div key={uuid()} className="review-item">
```js
{reviews.map(v => (
   <div key={uuid()} className="review-item">
     ...
   </div>
)}
```

2020-12-01 04:27 UTC, futianshen commented on src/components/review/ReviewAdminItem.tsx
> +    onRefetch: refetch,
Keep the naming consistent
```js
{
   loadingReviews: loading,
   reviews,
   errorReviews: error,
   refetchReviews: refetch
}
```

2020-12-01 05:18 UTC, Elantris requested changes

2020-12-01 05:18 UTC, Elantris commented on src/helpers/translation.ts
> +    },
the count in messages should be variables

2020-12-01 05:18 UTC, Elantris commented on src/types/review.ts
> +export type reviewRoleName = 'app-owner' | 'content-creator'
remove unused type definition

2020-12-01 05:18 UTC, Elantris commented on src/types/review.ts
> +} | null
type definition of objects should not union with `null`

2020-12-01 05:18 UTC, Elantris commented on src/components/review/ReviewCollectionBlock.tsx
> +  const reviewMemberItemRef = useRef() as React.RefObject<ReviewMemberItemRef>
NITS: interesting flow of ref 🤔

2020-12-02 04:49 UTC, Elantris commented on src/helpers/index.ts
> +}
don't use static string of specific language in translation

2020-12-03 09:45 UTC, merged