Feature/haohaoming homepage section
urfit-tech/lodestar-app pull request #148
Opened 2022-01-21 09:28 UTC by sunnylochun

2022-01-21 09:29 UTC, sunnylochun commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2)【站台】桃桃喜客製站轉標準站[0]](https://trello.com/c/raMmL3sY/2983-2%E3%80%90%E7%AB%99%E5%8F%B0%E3%80%91%E6%A1%83%E6%A1%83%E5%96%9C%E5%AE%A2%E8%A3%BD%E7%AB%99%E8%BD%89%E6%A8%99%E6%BA%96%E7%AB%990)

2022-01-24 02:20 UTC, emily40830 requested changes

2022-01-24 02:20 UTC, emily40830 commented on src/components/page/HaohaomingSection/Banner.tsx
> +            </Content>
Because our repo is open source, this content may not been located at script file.
use `app_page_section.options` to save contents is preferred.

2022-01-24 02:20 UTC, emily40830 commented on src/components/page/HaohaomingSection/Cover.tsx
> +          </SubTitle>
same as above.

2022-01-24 02:20 UTC, emily40830 commented on src/components/page/HaohaomingSection/FAQs.tsx
> +]
same as above.

2022-01-24 02:20 UTC, emily40830 commented on src/components/page/HaohaomingSection/Philosophy.tsx
> +            </p>
same as above.

2022-01-24 02:20 UTC, emily40830 commented on src/components/page/HaohaomingSection/Recommend.tsx
> +]
same as above

2022-01-24 02:20 UTC, emily40830 commented on src/components/page/HaohaomingSection/Reviews.tsx
> +
same as above.

2022-01-24 02:20 UTC, emily40830 commented on src/components/page/HaohaomingSection/TeacherIntroduction.tsx
> +              </Content>
same as above.

2022-01-24 07:47 UTC, emily40830 approved these changes

2022-01-24 07:48 UTC, merged