[BUGFIX] if program is private , hide the program
urfit-tech/lodestar-app pull request #169
Opened 2022-04-26 05:30 UTC by Ponchimeow

+ add is_private is false
+ add is_deleted is false

2022-04-26 05:30 UTC, Ponchimeow commented
![](https://github.trello.services/images/mini-trello-icon.png) [【篩選器】私密發布的課程不要出現在搜尋結果](https://trello.com/c/SG6QgCBm/3301-%E3%80%90%E7%AF%A9%E9%81%B8%E5%99%A8%E3%80%91%E7%A7%81%E5%AF%86%E7%99%BC%E5%B8%83%E7%9A%84%E8%AA%B2%E7%A8%8B%E4%B8%8D%E8%A6%81%E5%87%BA%E7%8F%BE%E5%9C%A8%E6%90%9C%E5%B0%8B%E7%B5%90%E6%9E%9C)

2022-04-28 02:06 UTC, kkshyu requested changes

2022-04-28 02:06 UTC, kkshyu commented on src/pages/AdvancedSearchPage.tsx
> +    is_deleted: { _eq: false },
`is_deleted` should be filtered by hasura

2022-04-28 03:50 UTC, kkshyu approved these changes

2022-04-28 03:50 UTC, merged