[Bugfix] member field setting
urfit-tech/lodestar-app pull request #307
Opened 2023-02-06 15:05 UTC by brain00021

2023-02-06 15:06 UTC, brain00021 commented
![](https://github.trello.services/images/mini-trello-icon.png) [【會員資料】新增自訂欄位顯示控制項](https://trello.com/c/35TR0LEy/15-%E3%80%90%E6%9C%83%E5%93%A1%E8%B3%87%E6%96%99%E3%80%91%E6%96%B0%E5%A2%9E%E8%87%AA%E8%A8%82%E6%AC%84%E4%BD%8D%E9%A1%AF%E7%A4%BA%E6%8E%A7%E5%88%B6%E9%A0%85)

2023-02-07 15:29 UTC, Ponchimeow commented on src/components/profile/ProfileOtherAdminCard.tsx
> +                })
reference: https://hasura.io/docs/latest/mutations/postgres/update/#multiple-updates

2023-02-07 15:30 UTC, Ponchimeow requested changes
can optimize updateMmeberProperty method,

2023-02-08 14:41 UTC, Ponchimeow approved these changes

2023-02-08 15:56 UTC, merged