Feature/global signup property modal
urfit-tech/lodestar-app pull request #311
Opened 2023-02-20 15:38 UTC by Ponchimeow

2023-02-20 15:39 UTC, Ponchimeow commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) 【資料】若註冊時有必填資料，偵測有缺資料就自動跳出modal提醒填寫 [2]](https://trello.com/c/Jw1gV6Lm/4133-3-%E3%80%90%E8%B3%87%E6%96%99%E3%80%91%E8%8B%A5%E8%A8%BB%E5%86%8A%E6%99%82%E6%9C%89%E5%BF%85%E5%A1%AB%E8%B3%87%E6%96%99%EF%BC%8C%E5%81%B5%E6%B8%AC%E6%9C%89%E7%BC%BA%E8%B3%87%E6%96%99%E5%B0%B1%E8%87%AA%E5%8B%95%E8%B7%B3%E5%87%BAmodal%E6%8F%90%E9%86%92%E5%A1%AB%E5%AF%AB-2)

2023-02-22 07:21 UTC, HLTVProxy requested changes

2023-02-22 07:21 UTC, HLTVProxy commented on src/components/common/SignupPropertyModal.tsx
> +      // closable={false}
remove unuse property

2023-02-22 07:21 UTC, HLTVProxy commented on src/components/common/SignupPropertySection.tsx
> +                .then(() => {})
add message toast to display update successfully

2023-02-24 08:41 UTC, merged