change programe menu setting for exam
urfit-tech/lodestar-app pull request #314
Opened 2023-03-08 15:31 UTC by brain00021

修改menu 考試設定
例如滿分100分 及格60分
如果學生未答題為null，百分比為0%（空心圓圈）
如果學生答題30分，百分比為50%（灰勾勾）
如果學生答題60分，百分比為100%（實心勾勾）
如果學生答題80分，百分比為100%（實心勾勾）

2023-03-10 17:37 UTC, brain00021 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1) 【學習進度】學習進度表上測驗顯示通過也有測驗通過時間，但總課程完成率為0%](https://trello.com/c/yyLfjwGb/17-1-%E3%80%90%E5%AD%B8%E7%BF%92%E9%80%B2%E5%BA%A6%E3%80%91%E5%AD%B8%E7%BF%92%E9%80%B2%E5%BA%A6%E8%A1%A8%E4%B8%8A%E6%B8%AC%E9%A9%97%E9%A1%AF%E7%A4%BA%E9%80%9A%E9%81%8E%E4%B9%9F%E6%9C%89%E6%B8%AC%E9%A9%97%E9%80%9A%E9%81%8E%E6%99%82%E9%96%93%EF%BC%8C%E4%BD%86%E7%B8%BD%E8%AA%B2%E7%A8%8B%E5%AE%8C%E6%88%90%E7%8E%87%E7%82%BA0)

2023-03-13 13:41 UTC, Ponchimeow commented on src/components/program/ProgramContentMenu.tsx
> +    progress => progress.programContentType !== 'exam' && progress.programContentType !== 'text',
filter exam and exercise, not text

2023-03-13 16:37 UTC, Ponchimeow commented on src/components/program/ProgramContentMenu.tsx
> +// 這一塊跑 menu content的內容
tranfer to english?
or remove it

2023-03-13 16:39 UTC, Ponchimeow commented on src/components/program/ProgramContentMenu.tsx
> +  const [passExam, setPassExam] = useState([])
type maybe string[] ?

2023-03-13 16:40 UTC, Ponchimeow commented on src/components/program/ProgramContentMenu.tsx
> +  setPassExam: any
should not be any

2023-03-14 17:17 UTC, Ponchimeow commented on src/components/program/ProgramContentMenu.tsx
> +  const { currentExamData, gaindedPointsTotal, refetchCurrentExamData, questionPointsTotal } =
is gained not gainded

2023-03-14 17:26 UTC, Ponchimeow commented on src/components/program/ProgramContentMenu.tsx
> +  const { currentExamData, gaindedPointsTotal, refetchCurrentExamData, questionPointsTotal } =
choose a method to process
1. add loading and error status
2. remove variable which is declared but its value is never read

2023-03-15 03:39 UTC, Ponchimeow commented on src/components/program/ProgramContentMenu.tsx
> +        if (type === 'text' || type === 'exam') {
filter exam and exercise, not text

2023-03-15 03:41 UTC, Ponchimeow commented on src/contexts/ProgressContext.tsx
> +                  programContentType: contentBody.type,
this type is result from program_content_body, prefer the variable name is programCotnentBodyType

2023-03-15 03:42 UTC, Ponchimeow commented on src/hooks/exam.ts
> +  const { loading, error, data, refetch } = useQuery<
return loading, error

2023-03-15 10:27 UTC, Ponchimeow commented on src/components/program/ProgramContentMenu.tsx
> +  const { currentExamData, gaindedPointsTotal, refetchCurrentExamData, questionPointsTotal } =
in the feature, you just need the exam total score, exam passing score and exercise gained points

you could refer the following information

```typescript
const useExamExercise = (
  programContentId: string,
  memberId: string,
  exerciseId?: string | null
) => {
  const condition: hasura.GET_EXAM_EXERCISEVariables["condition"] = {
    id: exerciseId ? { _eq: exerciseId } : undefined,
    program_content_id: { _eq: programContentId },
    member_id: exerciseId ? undefined : { _eq: memberId },
    answer: { _is_null: false },
  };
  const { loading, error, data } = useQuery<
    hasura.GET_EXAM_EXERCISE,
    hasura.GET_EXAM_EXERCISEVariables
  >(gql`
    query GET_EXAM_EXERCISE($condition: exercise_bool_exp!) {
      exercise(where: $condition) {
        id
        exercise_publics {
          exercise_id
          question_points
        }
        exam {
          id
          passing_score
        }
      }
    }
  `);
};

```

2023-03-15 14:16 UTC, brain00021 commented on src/components/program/ProgramContentMenu.tsx
> +  const { currentExamData, gaindedPointsTotal, refetchCurrentExamData, questionPointsTotal } =
fixed

2023-03-15 14:20 UTC, brain00021 commented on src/hooks/exam.ts
> +  const { loading, error, data, refetch } = useQuery<
fix

2023-03-15 14:43 UTC, Ponchimeow requested changes
please optimize it

2023-03-21 13:29 UTC, Ponchimeow commented on src/components/program/ProgramContentMenu.tsx
> +      let { gainedPointsTotal, passingScore, questionPointsTotal } = currentExamExerciseData[0]
see exam.ts line 235, could get data directly

2023-03-21 13:31 UTC, Ponchimeow commented on src/hooks/exam.ts
> +      : data?.exercise.map(Citem => {
data?.exercise?.[0].(Citem => ...)

2023-03-21 13:31 UTC, Ponchimeow commented on src/components/program/ProgramContentMenu.tsx
> +    // let {} = currentExercise[0]
remove it

2023-03-21 14:11 UTC, Ponchimeow commented on src/hooks/exam.ts
> +            question_started_at
`question_started_at` is unnecessary column

2023-03-21 14:42 UTC, Ponchimeow commented on src/hooks/exam.ts
> +        })
```typescript
  const currentExamExerciseData: {
    passingScore: number
    gainedPointsTotal: number
    questionPointsTotal: number
  } = {
    passingScore: data?.exercise?.[0].exam?.passing_score || 0,
    gainedPointsTotal:
      data?.exercise?.[0].exercise_publics.reduce((acc, item) => {
        return acc + Number(item?.gained_points || 0)
      }, 0) || 0,
    questionPointsTotal:
      data?.exercise?.[0].exercise_publics.reduce((acc, item) => {
        return acc + Number(item?.question_points || 0)
      }, 0) || 0,
  }
```

2023-03-21 14:54 UTC, Ponchimeow commented on src/components/program/ProgramContentMenu.tsx
> +  const type = contentCurrentProgress?.programCotnentBodyType || ''
typo
programContentBodyType

2023-03-27 13:20 UTC, merged

2023-04-12 06:01 UTC, kkshyu commented on src/components/program/ProgramContentMenu.tsx
> +  const [passExam, setPassExam] = useState([])
it will be `never[]`