fix: business member
urfit-tech/lodestar-app pull request #325
Opened 2023-03-24 04:35 UTC by HLTVProxy

- fix company title is required in company register
- fix  "公司抬頭、公司統編、公司類型、公司地址、公司負責人" is required in company profile settings
- fix 公司類型 is selector not text field
- fix ProfileAccountAdminCard error message

2023-03-24 04:36 UTC, HLTVProxy commented
![](https://github.trello.services/images/mini-trello-icon.png) [【建立公司、公司設定、作品管理】細項修改PART02](https://trello.com/c/rD8pzXUS/4271-%E3%80%90%E5%BB%BA%E7%AB%8B%E5%85%AC%E5%8F%B8%E3%80%81%E5%85%AC%E5%8F%B8%E8%A8%AD%E5%AE%9A%E3%80%81%E4%BD%9C%E5%93%81%E7%AE%A1%E7%90%86%E3%80%91%E7%B4%B0%E9%A0%85%E4%BF%AE%E6%94%B9part02)

2023-03-26 06:10 UTC, Ponchimeow commented on src/components/profile/ProfileBasicBusinessCard.tsx
>                  initialValue: defaultValue,
need to handle display value if form item is select component
<img width="366" alt="image" src="https://user-images.githubusercontent.com/28040359/227755774-aa686e5d-6c1f-48e1-8251-cfed5b486764.png">

2023-03-26 11:34 UTC, Ponchimeow requested changes
adjust select component default value

2023-03-27 04:47 UTC, Ponchimeow approved these changes

2023-03-27 07:31 UTC, merged