feat: add inbound after submitting meetus page
urfit-tech/lodestar-app pull request #390
Opened 2023-07-28 08:04 UTC by YohaLin

1. add 'inbound_英鎊' in 廣告素材  after submitting meetus page if appId equals 'sixdigital'.
2. refactor code to insert 'inbound_英鎊'

2023-07-28 08:06 UTC, YohaLin commented
https://trello.com/c/cZwrZGun/1970-%E3%80%90%E8%87%AA%E8%A8%82%E6%AC%84%E4%BD%8D%E3%80%91%E8%87%AA%E5%8B%95%E5%8C%96%E6%8E%9B%E5%BB%A3%E5%91%8A%E7%B4%A0%E6%9D%90%E8%87%AA%E8%A8%82%E6%AC%84%E4%BD%8D

2023-07-28 08:23 UTC, YohaLin commented
![](https://github.trello.services/images/mini-trello-icon.png) [【自訂欄位】自動化掛廣告素材自訂欄位](https://trello.com/c/cZwrZGun/1970-%E3%80%90%E8%87%AA%E8%A8%82%E6%AC%84%E4%BD%8D%E3%80%91%E8%87%AA%E5%8B%95%E5%8C%96%E6%8E%9B%E5%BB%A3%E5%91%8A%E7%B4%A0%E6%9D%90%E8%87%AA%E8%A8%82%E6%AC%84%E4%BD%8D)

2023-08-02 03:23 UTC, Ponchimeow commented on src/pages/MeetingPage/MeetingPage.tsx
> +  const isInsertingAdProperty = JSON.parse(settings['custom.ad_property.list']).map(
map will return value
use some method

FYI
https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2023-08-02 04:08 UTC, Ponchimeow commented on src/pages/MeetingPage/MeetingPage.tsx
> +        })
if current member is exist, will missing `insrt member task`、`update member phone`、`update membr categories`、`update member`、`update tracking log ( utm )`

call create-lead api
reffer:  https://github.com/urfit-tech/lodestar-app-backend/blob/develop/src/controllers/sys.controller.ts:L1233

2023-08-02 04:09 UTC, Ponchimeow requested changes
see comment

2023-08-02 07:01 UTC, Ponchimeow approved these changes

2023-08-02 07:01 UTC, merged