fix: isEnrolled AppointmentItem onClick
urfit-tech/lodestar-app pull request #415
Opened 2023-08-30 07:05 UTC by LoisChen68

2023-08-30 07:20 UTC, LoisChen68 commented
![](https://github.trello.services/images/mini-trello-icon.png) [【預約服務】同一時段可被相同學員重複預約](https://trello.com/c/k89sCTBx/2308-%E3%80%90%E9%A0%90%E7%B4%84%E6%9C%8D%E5%8B%99%E3%80%91%E5%90%8C%E4%B8%80%E6%99%82%E6%AE%B5%E5%8F%AF%E8%A2%AB%E7%9B%B8%E5%90%8C%E5%AD%B8%E5%93%A1%E9%87%8D%E8%A4%87%E9%A0%90%E7%B4%84)

2023-08-31 07:23 UTC, Ponchimeow approved these changes

2023-08-31 07:23 UTC, Ponchimeow commented on src/components/appointment/AppointmentPeriodCollection.tsx
> +                >
can remove onClick event

2023-09-01 02:44 UTC, clothe09986 requested changes

2023-09-01 02:44 UTC, clothe09986 commented on src/components/appointment/AppointmentPeriodCollection.tsx
> +                </div>
```
<div
    key={period.id}
    onClick={() => {
      if (isAuthenticated) {
        if (!period.currentMemberBooked) {
          onClick && onClick(period)
        }
      } else {
        setAuthModalVisible && setAuthModalVisible(true)
      }
    }}
>
  {ItemElem}
</div>
```

I think this code is better and cleaner.

2023-09-01 02:48 UTC, clothe09986 requested changes

2023-09-01 02:48 UTC, clothe09986 commented on src/components/appointment/AppointmentPeriodCollection.tsx
>                    {ItemElem}
```
<div
    key={period.id}
    onClick={() => {
      if (isAuthenticated) {
        if (!period.currentMemberBooked) {
          onClick && onClick(period)
        }
      } else {
        setAuthModalVisible && setAuthModalVisible(true)
      }
    }}
>
  {ItemElem}
</div>
```

I think this code is better and cleaner.

2023-09-01 02:54 UTC, clothe09986 approved these changes

2023-09-01 02:54 UTC, merged