Feature/add paypal checkout
urfit-tech/lodestar-app pull request #48
Opened 2021-07-16 01:58 UTC by emily40830

2021-07-16 02:05 UTC, emily40830 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5)【金流】paypal串接[2]](https://trello.com/c/CfU1fRvV/2199-5%E3%80%90%E9%87%91%E6%B5%81%E3%80%91paypal%E4%B8%B2%E6%8E%A52)

2021-07-19 03:21 UTC, kkshyu commented on src/helpers/translation.ts
> +  },
NITS: `E_PAYPAL_SETUP` is better

2021-07-19 03:21 UTC, kkshyu commented on src/helpers/translation.ts
> +  },
what's this?

2021-07-19 03:21 UTC, kkshyu commented on src/pages/PaymentPage.tsx
> +                  window.location.href = result.html
why not using `setPayForm` like `spgateway` and `parenting`

2021-07-20 04:41 UTC, kkshyu requested changes
plz learn how to solve the conflict

2021-07-20 11:15 UTC, kkshyu approved these changes

2021-07-20 11:16 UTC, kkshyu commented on src/helpers/translation.ts
> +  },
i see. we can discuss about this in the code review meeting.
i prefer E_NAMESPACE_ACTION pattern

2021-07-20 11:16 UTC, merged