Feature/blog activity category
urfit-tech/lodestar-app pull request #52
Opened 2021-07-20 06:13 UTC by Ponchimeow

2021-07-20 06:13 UTC, Ponchimeow commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) 【分類】部落格分類獨立在文章區、活動分類獨立顯示](https://trello.com/c/GlF8Cyyg/2264-2-%E3%80%90%E5%88%86%E9%A1%9E%E3%80%91%E9%83%A8%E8%90%BD%E6%A0%BC%E5%88%86%E9%A1%9E%E7%8D%A8%E7%AB%8B%E5%9C%A8%E6%96%87%E7%AB%A0%E5%8D%80%E3%80%81%E6%B4%BB%E5%8B%95%E5%88%86%E9%A1%9E%E7%8D%A8%E7%AB%8B%E9%A1%AF%E7%A4%BA)

2021-07-20 11:21 UTC, kkshyu requested changes

2021-07-20 11:21 UTC, kkshyu commented on src/pages/BlogPostPage.tsx
> +                <Link key={tag} to={`/posts/?categories=${tag}`} className="mr-2">
Do not need to change this one. we should support two kinds of query params: tags and categories
not change all the tags to categories

2021-07-20 11:21 UTC, kkshyu commented on src/pages/BlogPostCollectionPage.tsx
> +  const [categories] = useQueryParam('categories', StringParam)
Do not need to change this one. we should support two kinds of query params: tags and categories
not change all the tags to categories

2021-07-21 03:38 UTC, kkshyu commented on src/hooks/blog.ts
> +              post.post_tags.some(postTag => filter.categories?.includes(postTag.tag_name)),
if `tags` were set, need to filter, too.

2021-07-21 03:38 UTC, kkshyu commented on src/pages/BlogPostCollectionPage.tsx
> +              ))}
there is optional chaining already, don't need to have the condition

```ts
{
    !categories && tags?.split(',').map(tag => (
                <span key={tag} className="ml-2">
                  #{tag}
                </span>
              ))
}
```

2021-07-21 04:39 UTC, kkshyu approved these changes

2021-07-21 04:39 UTC, merged