Feat/add member activity rights page
urfit-tech/lodestar-app pull request #535
Opened 2024-04-15 10:01 UTC by TedxTed

# Activity Ticket Page Instructions

## Overview
Switch the usage from `order_product` route to the new `activity_ticket` route. Introduce a new page called `ActivityTicketDetailsPage` and employ the `activity/member-right` API. Additionally, a new hook named `activityTicket.ts` will be created.

## Preparation Steps

### Change the Product Route
Modify the endpoint configuration in the product route as follows:

**File**: `src/helpers`  
**Line**: #506

**Original**:  
```javascript
`${process.env.REACT_APP_LODESTAR_SERVER_ENDPOINT}${route}${memberId ? `/?memberId=${memberId}` : ''}`,
```

**Updated**:  
```javascript
`https://demomo.kolable.dev/api/v2${route}${memberId ? `/?memberId=${memberId}` : ''}`,
```

### Set Up the Local Lodestar Server
- **Branch to use**: `feat/member-activity-ticket-right-api`

### Update the Lodestar Server Environment Route
Change the lodestar-server environment route to point to localhost on port 8081.

## Testing Procedure

### Access the Member Page
Navigate to the member page at the following URL to view all the member's activity tickets:

**URL**:  
`http://localhost:3333/members/793733e7-c270-4db1-ae71-562984265429?tabkey=activity-ticket`

On this page, each link should direct to the `ActivityTicketDetailsPage`. There are two scenarios to test:

1. **No Session Query String**:  
   URL: `http://localhost:3333/activity_ticket/2965b630-1e86-4d05-a5f6-b2410768f5f1`

2. **With Session Query String**:  
   URL: `http://localhost:3333/activity_ticket/2965b630-1e86-4d05-a5f6-b2410768f5f1?session=39efb645-aea6-4a7b-9002-66449197aef1`

2024-04-15 10:03 UTC, TedxTed commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3)【活動】權益判斷另開API [2]](https://trello.com/c/Lvk4JOSt/5195-3%E3%80%90%E6%B4%BB%E5%8B%95%E3%80%91%E6%AC%8A%E7%9B%8A%E5%88%A4%E6%96%B7%E5%8F%A6%E9%96%8Bapi-2)

2024-04-23 19:38 UTC, LoisChen68 requested changes

2024-04-24 08:16 UTC, LoisChen68 requested changes

2024-04-29 07:34 UTC, Ponchimeow commented on src/pages/MemberPage/ActivityTicketCollectionBlock.tsx
> +  const sessions = tickets
add `.filter(ticket => ticket.sessions.length > 0)`

2024-04-30 07:42 UTC, merged

2024-05-22 05:08 UTC, kkshyu commented on src/hooks/activityTicket.ts
> +    [currentMemberId, activityTicketId],
FYI: https://github.com/xiaohesong/TIL/blob/master/front-end/react/overreact/%E4%B8%80%E4%BB%BD%E5%AE%8C%E6%95%B4%E7%9A%84useEffect%E6%8C%87%E5%8D%97.md

2024-05-22 05:18 UTC, kkshyu commented on src/pages/ActivityTicketDetailsPage.tsx
> +  }, [activityTicketData])
can also use `useReducer`