feat: membership card can display products
urfit-tech/lodestar-app pull request #613
Opened 2024-10-02 08:09 UTC by Ponchimeow

2024-10-02 08:21 UTC, Ponchimeow commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2)【會員卡管理】後台優惠條件設定要可以選到預約](https://trello.com/c/1rYn3NBN/5586-2%E3%80%90%E6%9C%83%E5%93%A1%E5%8D%A1%E7%AE%A1%E7%90%86%E3%80%91%E5%BE%8C%E5%8F%B0%E5%84%AA%E6%83%A0%E6%A2%9D%E4%BB%B6%E8%A8%AD%E5%AE%9A%E8%A6%81%E5%8F%AF%E4%BB%A5%E9%81%B8%E5%88%B0%E9%A0%90%E7%B4%84)

2024-10-02 17:16 UTC, TedxTed requested changes

2024-10-02 17:16 UTC, TedxTed commented on src/components/membershipCard/MembershipCardTermsModal.tsx
> +  const generateProductLink = (details: { productName: string; id: string; creatorId: string }) => {
since id and creatorId are just variations of the same thing (a unique identifier) ,maybe we can combine them as `resourceId` to keep it simple

2024-10-02 17:16 UTC, TedxTed commented on src/components/membershipCard/MembershipCardTermsModal.tsx
> +                          creatorId: discount.product.details?.creatorId || '',
same as above

2024-10-03 02:22 UTC, TedxTed approved these changes

2024-10-03 02:22 UTC, merged