Bugfix/activity session item
urfit-tech/lodestar-app pull request #63
Opened 2021-08-02 06:56 UTC by futianshen

2021-08-02 06:59 UTC, futianshen commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5)【活動】1 對多線上直播功能 [4]](https://trello.com/c/GR7Wm0x1/2217-5%E3%80%90%E6%B4%BB%E5%8B%95%E3%80%911-%E5%B0%8D%E5%A4%9A%E7%B7%9A%E4%B8%8A%E7%9B%B4%E6%92%AD%E5%8A%9F%E8%83%BD-4)

2021-08-03 15:33 UTC, kkshyu requested changes

2021-08-03 15:33 UTC, kkshyu commented on src/components/activity/ActivitySessionItem.tsx
>    renderAttend?: React.ReactNode
`renderProps` should be a function with props not a component
if we want to use a component, please use `location` instead of `renderLocation`

2021-08-03 15:33 UTC, kkshyu commented on src/components/activity/ActivitySessionItem.tsx
> +        {renderLocation || (
plz use function instead, ex.

```js
{
    renderLocation?.(someProps) || {
        defaultRenderer
    }
}
```

an idea to think about:

```ts
type LocationProps = { sessionType: string }
const ActivitySessionItem = ({ renderLocation }) => {
    const locationProps = { sessionType: "online" }
    return (
        <div>
            { renderLocation?.(locationProps) || renderDefaultLocation(locationProps)}
        </div>
    )
}

const renderDefaultLocation = (props: LocationProps ) => {
    return ...
}
```

2021-08-03 15:33 UTC, merged