feat: layout.language_sorted_list appSettings
urfit-tech/lodestar-app pull request #637
Opened 2024-11-29 08:16 UTC by LoisChen68

2024-11-29 08:17 UTC, LoisChen68 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1)【多國語系】調整語言選單順序](https://trello.com/c/JMingZhB/5657-1%E3%80%90%E5%A4%9A%E5%9C%8B%E8%AA%9E%E7%B3%BB%E3%80%91%E8%AA%BF%E6%95%B4%E8%AA%9E%E8%A8%80%E9%81%B8%E5%96%AE%E9%A0%86%E5%BA%8F)

2024-12-02 03:18 UTC, TedxTed requested changes

2024-12-02 03:18 UTC, TedxTed commented on src/components/common/Footer/DefaultFooter.tsx
> +  const languagesList = sortedLanguagesList.length > 0 ? sortedLanguagesList : SUPPORTED_LOCALES
這一段邏輯，在各檔案中重複性很高且我擔心若有其他人要使用LanguageList 但忽略掉要做這些邏輯的調整時會有錯誤，是否可以統一方法，像是customhook的方式(或其他)來處理這段，解決重複邏輯及使用layout.language_sorted_list時要注意特定邏輯的問題

2024-12-03 07:22 UTC, LoisChen68 commented on src/components/common/Footer/DefaultFooter.tsx
> +  const languagesList = sortedLanguagesList.length > 0 ? sortedLanguagesList : SUPPORTED_LOCALES
adjusted.

2024-12-03 08:02 UTC, Ponchimeow approved these changes

2024-12-03 08:02 UTC, merged