Bugfix/fix display format for price
urfit-tech/lodestar-app pull request #64
Opened 2021-08-03 09:49 UTC by emily40830

2021-08-03 09:49 UTC, emily40830 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) 【簡介頁、課程管理】訂閱課程方案，沒有正確顯示代幣+創建銷售方案無法選取幣值](https://trello.com/c/GNQmxICT/2280-2-%E3%80%90%E7%B0%A1%E4%BB%8B%E9%A0%81%E3%80%81%E8%AA%B2%E7%A8%8B%E7%AE%A1%E7%90%86%E3%80%91%E8%A8%82%E9%96%B1%E8%AA%B2%E7%A8%8B%E6%96%B9%E6%A1%88%EF%BC%8C%E6%B2%92%E6%9C%89%E6%AD%A3%E7%A2%BA%E9%A1%AF%E7%A4%BA%E4%BB%A3%E5%B9%A3%E5%89%B5%E5%BB%BA%E9%8A%B7%E5%94%AE%E6%96%B9%E6%A1%88%E7%84%A1%E6%B3%95%E9%81%B8%E5%8F%96%E5%B9%A3%E5%80%BC)

2021-08-03 16:35 UTC, kkshyu requested changes

2021-08-03 16:35 UTC, kkshyu commented on src/components/common/PriceLabel.tsx
> +    })
use the `currencyFormatter` in the utils from the other PR
btw, I thought `formatCurrency()` is the better naming

2021-08-03 16:35 UTC, kkshyu commented on src/containers/common/AppContext.tsx
> +    [currencyId: string]: { id: string; label: string | null; unit: string | null; minor_units: number | null }
please use camelCase in the JS

2021-08-03 16:35 UTC, kkshyu commented on src/hooks/common.ts
> +          currencyId: data.program_plan_by_pk.currency_id || 'TWD',
please use the currency ID from the AppContext as the default

2021-08-05 14:46 UTC, kkshyu approved these changes

2021-08-05 14:46 UTC, kkshyu commented on src/hooks/util.ts
> +    const currentCurrencyId = currencyId || settings['currency_id'] || 'TWD'
put "TWD" into environment variables

2021-08-05 14:46 UTC, merged